# Конфигурация Docker

version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_DSN: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
volumes:
  postgres_data: